services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: churn_api
    ports:
      - "8001:8000"
    restart: always
    networks:
      - churn_network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: churn_ui
    ports:
      - "8503:8501"
    depends_on:
      - api
    restart: always
    networks:
      - churn_network
      
networks:
  churn_network:
    driver: bridge
    