version: "3.8"

services:
  api:
    image: riya7737/customer-churn-prediction-api:latest
    container_name: churn_api
    ports:
      - "8001:8000"
    restart: always
    networks:
      - churn_network

  ui:
    image: riya7737/customer-churn-prediction-frontend:latest
    container_name: churn_ui
    ports:
      - "8503:8501"
    depends_on:
      - api
    restart: always
    networks:
      - churn_network

networks:
  churn_network:
    driver: bridge